sudo: required

language: python

python:
  - 3.6

services:
  - docker

before_install:
  - sudo sysctl -w vm.max_map_count=262144
  - sudo service docker restart
  - docker pull centos:7
  - docker images

install:
  - pip install -r requirements.txt

script:
  - VERSION=$(curl -s https://crate.io/versions.json | grep crate_testing | tr -d '" ' | cut -d ":" -f2)
  - ./update.py --cratedb-version ${VERSION} --platform "x64_linux" > amd64/crate/Dockerfile
  - PATH_TO_IMAGE=amd64/crate zope-testrunner --path . -s tests --color

notifications:
  email: false
